# This is a basic workflow to help you get started with Actions

name: ADF-DEPLOY

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "adf_publish" branch
  #push:
  #  branches: [ "adf_publish" ]
  #pull_request:
  #  branches: [ "adf_publish" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true     
      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          # Data Factory resource group name
          resourceGroupName: ADF-PIPELINE-UAT
          # Data factory name
          dataFactoryName: ADF-GITHUB-PIPELINE-UAT
          # ARM template file name
          armTemplateFile: ./ADF-GITHUB-PIPELINE-TEST/ARMTemplateForFactory.json # optional, default is ARMTemplateForFactory.json
          # ARM template parameters file name
          armTemplateParametersFile: ./ADF-GITHUB-PIPELINE-TEST/ARMTemplateParametersForFactory.json # optional, default is ARMTemplateParametersForFactory.json
          # Parameters which will be replaced in the ARM template
          #additionalParameters: # optional, default is 
          # Parameters which skip the Az module installation
          #skipAzModuleInstallation: # optional, default is false
